apiVersion: v1
kind: Service
metadata:
  name: appnamespace-nats-service
  namespace: appnamespace
spec:
  externalName: labs-nats-cluster.nats-io.svc.cluster.local
  ports:
  - port: 4222
    protocol: TCP
    targetPort: 4222
  type: ExternalName
