apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  labels:
    app: nats
    nats_cluster: labs-nats-cluster
  name: labs-nats-cluster-lb
  namespace: nats-io
spec:
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges:
  - 10.10.0.0/16 # VPC CIDR
  ports:
  - name: client
    nodePort: 30667
    port: 4222
    protocol: TCP
    targetPort: 4222
  selector:
    app: nats
    nats_cluster: labs-nats-cluster
  type: LoadBalancer
