apiVersion: v1
kind: Service
metadata:
  name: labs-nats-cluster-lb
  namespace: nats-io
  labels:
    app: nats
    nats_cluster: labs-nats-cluster
spec:
  ports:
  - name: client
    port: 4222
    protocol: TCP
    targetPort: 4222
  selector:
    app: nats
    nats_cluster: labs-nats-cluster
  type: LoadBalancer
  loadBalancerSourceRanges:
  - x.x.x.x/32 # IP Whitelist